=== ChaosKitten/Citizens/client/xml/asset.dtd
<!ELEMENT asset (description?,name?,vector*,texture,model)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT vector (x|y|z)*>
<!ELEMENT texture EMPTY>
<!ELEMENT model EMPTY>

<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>

<!ATTLIST asset
	name CDATA #REQUIRED
	type (building|player) #REQUIRED
	>

<!ATTLIST vector 
	type (position|orientation|scale) #REQUIRED
	>

<!ATTLIST texture 
	name CDATA #REQUIRED
	path CDATA #REQUIRED
	>

<!ATTLIST model 
	path CDATA #REQUIRED
	>

=== ChaosKitten/Citizens/client/buildings/hut.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE asset SYSTEM "../xml/asset.dtd">


<asset name="hut" type="building">
	
	<vector type="position">
		<x value="2000.0" />
		<y value="0.0" />
		<z value="2000.0" />
	</vector>
	<vector type="orientation">
		<x value="0.0" />
		<y value="0.0" />
		<z value="0.0" />
	</vector>
	<vector type="scale">
		<x value="200.0" />
		<y value="50.0" />
		<z value="200.0" />
	</vector>
	
	<texture name="base" path="hut.tga" />
	
	<model path="hut.ms3d" />

</asset>
