=== ChaosKitten/Citizens/client/xml/maptile.dtd
<!ELEMENT maptile (coordinates,asset*,building*,splat*)>
<!ELEMENT coordinates EMPTY>
<!ELEMENT asset (name,file)>
<!ELEMENT building (location,asset)>
<!ELEMENT location (vector)>
<!ELEMENT vector (x,y,z)>
<!ELEMENT splat (texture)>
<!ELEMENT texture (#PCDATA)>

<!ATTLIST maptile
	>

<!ATTLIST coordinates
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	>

<!ATTLIST asset
	type (building)
	>

<!ATTLIST building
	>

<!ATTLIST location
	>
	
<!ATTLIST vector 
	type (scale|orientation|position) #REQUIRED
	x CDATA "1"
	y CDATA "1"
	z CDATA "1"
	>

<!ATTLIST splat
	>

<!ATTLIST texture
	>

=== ChaosKitten/Citizens/client/Dummy_MapTiles/Village.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE maptile SYSTEM "../xml/maptile.dtd">

<maptile>
	<coordinates x="0" y="0" />
	<asset type="building">
		<name>hut</name>
		<file>buildings/hut.xml</file>
	</asset>
	<building>
		<location>
			<vector 
				type="position"
				x="2000.0"
				y="0.0"
				z="2000.0" />
			<vector 
				type="orientation"
				x="0.0"
				y="0.0"
				z="0.0" />
			<!-- note: you don't need to override the scale, this is just here to prove it's possible to -->
			<vector 
				type="scale"
				x="200.0"
				y="50.0"
				z="200.0" />
		</location>
		<!-- brings in the 'hut' asset for this location -->
		<asset>hut</asset>
	</building>
	<!-- splats onto the terrain (shadows, paths, weather effects, etc.) -->
	<splat>
		<texture>
			DummyMapTiles/village.bmp
		</texture>
		<!-- TODO: add support for this
		<shader>
			shaders/weather.gc
		</shader>
		-->
	</splat>


</maptile>
